### ISSUE TITLE
Intermittent failure where stacktrace is missing from the test result. 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/test-retry-gradle-plugin#144]
Gradle 7.5, JDK 17 on linux

After upgrading from `test-retry-gradle-plugin` `1.3.1` to `1.4.0` got an empty stacktrace on the test failure exception.
This only happens intermittently, but never saw this with `1.3.1` 

We have a `TestListener` that logs info about the error: 
```kotlin
   addTestListener(object : TestListener {
        override fun beforeSuite(suite: TestDescriptor?) = Unit
        override fun afterSuite(suite: TestDescriptor?, result: TestResult?) = Unit
        override fun beforeTest(testDescriptor: TestDescriptor?) = Unit

        override fun afterTest(testDescriptor: TestDescriptor?, result: TestResult?) {
            when (result?.resultType) {
                FAILURE -> {
                      logger.quiet(exception?.stackTrace?.first()?.fileName)
                 }
                }
                else -> {} // do nothing
            }
        }
    }
)
```

It resulted in this error on JDK 17: 
```
2022-08-19T23:38:40.8454892Z Caused by: java.util.NoSuchElementException: Array is empty.
2022-08-19T23:38:40.8455425Z 	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1013)
2022-08-19T23:38:40.8455841Z 	at my.Test_gradle$3$3.afterTest(test.gradle.kts:57)
2022-08-19T23:38:40.8456349Z 	at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
2022-08-19T23:38:40.8457066Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-08-19T23:38:40.8457878Z 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-08-19T23:38:40.8458743Z 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-08-19T23:38:40.8459503Z 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
2022-08-19T23:38:40.8460252Z 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:245)
2022-08-19T23:38:40.8460943Z 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:157)
2022-08-19T23:38:40.8461669Z 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
2022-08-19T23:38:40.8462389Z 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:346)
2022-08-19T23:38:40.8463072Z 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:249)
2022-08-19T23:38:40.8463740Z 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
2022-08-19T23:38:40.8464374Z 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
2022-08-19T23:38:40.8465108Z 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2022-08-19T23:38:40.8465881Z 	at jdk.proxy3/jdk.proxy3.$Proxy109.afterTest(Unknown Source)
2022-08-19T23:38:40.8466527Z 	at org.gradle.api.internal.tasks.testing.results.TestListenerAdapter.completed(TestListenerAdapter.java:50)
2022-08-19T23:38:40.8467262Z 	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
2022-08-19T23:38:40.8467962Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-08-19T23:38:40.8468707Z 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
```

**Comment by marcphilipp** [comment]
I think this would even happen without the test-retry plugin being applied. If you find a reliable reproducer, please let us know.
